name-template: 'Version $NEXT_PATCH_VERSION 🚀'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Nuevas Funcionalidades'
    labels: ['feature']
  - title: '🐛 Correcciones de Errores'
    labels: ['bug', 'hotfix']
  - title: '🛠️ Mejoras'
    labels: ['enhancement']
  - title: '🔧 Refactorización'
    labels: ['refactor']
change-template: '- $TITLE (#$NUMBER)'
template: |
  ## 📢 Cambios en esta versión
  
  $CHANGES

  ---
  ℹ️ **Notas:**  
  - Fecha de lanzamiento: $DATE  
  - Commits incluidos: [$PREVIOUS_TAG...$TAG](https://github.com/OWNER/REPO/compare/$PREVIOUS_TAG...$TAG)  
